version: '3'

services:
  app:
    build: .
    image: $DOCKER_IMAGE
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - $PORT:80
    restart: always
